### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by siner308** [siner308/ttbkk-web#1]
- [ ] google login
- [ ] place 등록

**Comment by siner308** [comment]
[ ] 쿠키를 사용하여 최근 조회했던 장소와 줌레벨 저장

**Comment by wooheewon** [comment]
별점 기능 : 카카오맵. 네이버지도 별점 불러오기 or 지인평가 평점

**Comment by wooheewon** [comment]
**별점 기능**

- [ ] 네이버 지도 / 카카오 맵 / 구글 맵 매장 별점 불러오기
- [ ] 별점 주기 / 별점 삭제
- [ ] 별정 평균 / 명수

**Comment by Albegam** [comment]
- [ ] 장소 생성 취소 시, 마커 및 좌표 리셋
- [ ] 일반 마커와 현재 선택 된 마커 차별성 (색, 크기 등)

**Comment by siner308** [comment]
- [ ] 장소 공유하기 기능 (개발조회 api 필요)

**Comment by siner308** [comment]
> * [ ]  장소 생성 취소 시, 마커 및 좌표 리셋
> * [ ]  일반 마커와 현재 선택 된 마커 차별성 (색, 크기 등)

https://github.com/siner308/ttbkk-web/issues/10
https://github.com/siner308/ttbkk-web/issues/11

**Comment by siner308** [comment]
> **별점 기능**
> 
> * [ ]  네이버 지도 / 카카오 맵 / 구글 맵 매장 별점 불러오기
> * [ ]  별점 주기 / 별점 삭제
> * [ ]  별정 평균 / 명수

별점 기능 구현 계획은 있으나, 타 서비스의 데이터를 가져와서 그대로 보여줄 생각은 없습니다.
추후 별점 남기는 기능을 구현 할 예정입니다
https://github.com/siner308/ttbkk-web/issues/13
